[command]
name = "execute"
description = "执行指定的BGA规划"
usage = "/bga:execute <plan_id> [options]"

[command.parameters]
plan_id = { type = "string", required = true, description = "规划编号，例如：P001" }
mode = { type = "string", required = false, description = "执行模式：parallel|sequential，默认parallel" }
tasks = { type = "string", required = false, description = "指定执行的任务ID，例如：1,3,5" }
force = { type = "boolean", required = false, description = "强制执行（跳过某些验证）" }
dry_run = { type = "boolean", required = false, description = "试运行模式（不实际执行）" }

[command.examples]
basic = "/bga:execute P001"
parallel = "/bga:execute P002 --mode=parallel"
specific_tasks = "/bga:execute P001 --tasks=1,3,5"
force_mode = "/bga:execute P002 --force"
dry_run = "/bga:execute P001 --dry-run"

[command.help]
text = """
执行指定编号的Background Agent规划。系统将按照规划中的
任务列表和依赖关系进行执行，并实时更新任务状态。

支持的参数：
- plan_id: 必填，规划编号（P001-P999）
- mode: 可选，执行模式
  * parallel: 并行执行（默认，适合无依赖冲突的任务）
  * sequential: 顺序执行（安全模式）
- tasks: 可选，只执行指定的任务ID（逗号分隔）
- force: 可选，强制执行（跳过某些验证，谨慎使用）
- dry_run: 可选，模拟执行但不实际操作

执行前会进行完整的上下文读取和依赖验证。
执行过程中会实时更新todolist.md中的任务状态。
执行完成后会自动生成详细的执行报告。
"""

[mcp]
server = "bga-server"
tool = "execute_plan"
timeout = 14400  # 4小时超时

[mcp.mapping]
plan_id = "plan_id"
execution_mode = "mode"
target_tasks = "tasks"
force_execution = "force"
dry_run_mode = "dry_run"