[command]
name = "feedback"
description = "管理BGA规划的反馈和建议"
usage = "/bga:feedback <plan_id> [action] [options]"

[command.parameters]
plan_id = { type = "string", required = true, description = "规划编号，例如：P001" }
action = { type = "string", required = false, description = "操作类型：add|view|update|delete，默认view" }
content = { type = "string", required = false, description = "反馈内容（action=add时必填）" }
type = { type = "string", required = false, description = "反馈类型：task_optimization|performance|security|user_experience|feature" }
status = { type = "string", required = false, description = "反馈状态：pending|processing|adopted|recorded|rejected" }
feedback_id = { type = "string", required = false, description = "反馈ID（update/delete时需要）" }

[command.examples]
view_all = "/bga:feedback P001"
add_feedback = "/bga:feedback P001 add --content='建议优化任务3的执行逻辑' --type=task_optimization"
update_status = "/bga:feedback P001 update --feedback-id=fb_001 --status=adopted"
view_by_type = "/bga:feedback P002 view --type=performance"

[command.help]
text = """
管理Background Agent规划的反馈和建议系统。
支持多方反馈收集和状态跟踪。

支持的操作：
- view: 查看反馈（默认操作）
- add: 添加新反馈
- update: 更新反馈状态
- delete: 删除反馈

反馈类型：
- task_optimization: 任务优化建议
- performance: 性能改进建议  
- security: 安全相关建议
- user_experience: 用户体验改进
- feature: 功能增强建议

反馈状态：
- pending: 待处理
- processing: 处理中
- adopted: 已采纳
- recorded: 已记录
- rejected: 已拒绝

系统会自动记录反馈时间、反馈者类型等元信息。
"""

[mcp]
server = "bga-server"
tool = "manage_feedback"
timeout = 60

[mcp.mapping]
target_plan = "plan_id"
operation = "action"
feedback_content = "content"
feedback_type = "type"
feedback_status = "status"
target_feedback_id = "feedback_id"